# Generated by Django 5.2.17 on 2026-09-10 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('price', models.PositiveIntegerField(verbose_name='Giá bán (đ)')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Giá gốc (đ)')),
                ('condition', models.CharField(choices=[('new', 'Mới 100%'), ('like-new', 'Như mới (95%+)'), ('used', 'Đã dùng')], default='used', max_length=20, verbose_name='Tình trạng')),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('phone', 'Điện thoại'), ('tablet', 'Tablet'), ('audio', 'Tai nghe / Âm thanh'), ('camera', 'Máy ảnh'), ('keyboard', 'Bàn phím / Phụ kiện PC'), ('gaming', 'Gaming'), ('clothes', 'Thời trang'), ('shoes', 'Giày dép'), ('bag', 'Balo & Túi'), ('accessory', 'Phụ kiện'), ('beauty', 'Mỹ phẩm'), ('books', 'Sách vở'), ('course', 'Tài liệu học'), ('study', 'Đồ học tập'), ('exam', 'Tài liệu ôn thi'), ('parttime', 'Tài liệu thực tập'), ('furniture', 'Nội thất'), ('kitchen', 'Đồ nhà bếp'), ('dorm', 'Đồ ký túc'), ('hostel', 'Đồ phòng trọ'), ('electric', 'Đồ điện tử'), ('sport', 'Thể thao'), ('bike', 'Xe đạp'), ('food', 'Đồ ăn & Thức uống')], max_length=20, verbose_name='Danh mục')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Khu vực')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Ảnh chính')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Người bán đã xác minh')),
                ('is_flash_sale', models.BooleanField(default=False, verbose_name='Đang Flash Sale')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Đã bán')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Đã duyệt hiển thị')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sản phẩm thanh lý',
                'verbose_name_plural': 'Sản phẩm thanh lý',
                'ordering': ['-created_at'],
            },
        ),
    ]
