# Generated by Django 5.2.17 on 2026-09-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Thương hiệu / Xuất xứ'),
        ),
        migrations.AddField(
            model_name='marketproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='market/', verbose_name='Ảnh sản phẩm (upload)'),
        ),
        migrations.AddField(
            model_name='marketproduct',
            name='ship_methods',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phương thức giao hàng'),
        ),
        migrations.AlterField(
            model_name='marketproduct',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ảnh chính (dán link)'),
        ),
    ]
