"""
Django settings for webbanhang project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import pymysql
pymysql.install_as_MySQLdb()
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@)@&h+kx)j)2jnwkucvf)m_(yabb@=9b8bht3wi5qi%=6)_@yn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.ngrok-free.app', 'localhost', '127.0.0.1']
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.ngrok.app'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ── Bắt buộc cho django-allauth (đăng nhập Google/Facebook) ──
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',

    'shop',
    'landing',
]

# Bắt buộc khi dùng django.contrib.sites (allauth yêu cầu)
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',   # bắt buộc với allauth bản mới
]

ROOT_URLCONF = 'stdshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Tự động cấp unread_notif_count cho MỌI template (dùng cho
                # badge icon chuông thông báo trong base.html) mà không cần
                # từng view phải tự truyền vào context.
                'shop.context_processors.notifications_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'stdshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'stdshop',
        "USER": "root",
        "PASSWORD": "HoChiMinh1890",
        "HOST": "localhost",
        "PORT": "3306",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/img/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'shop/static/img')

# ============================================================
#  ĐĂNG NHẬP MẠNG XÃ HỘI — Google / Facebook (qua django-allauth)
#  Zalo được viết thủ công trong views.py vì allauth chưa hỗ trợ sẵn.
# ============================================================

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',          # đăng nhập username/password gốc
    'allauth.account.auth_backends.AuthenticationBackend', # đăng nhập Google/Facebook
]

# Sau khi đăng nhập / đăng xuất (kể cả qua mạng xã hội) sẽ chuyển hướng về đâu
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/login/'

# Cấu hình allauth: không bắt buộc email xác minh (đơn giản hóa cho dự án),
# cho phép đăng nhập bằng username lẫn email
ACCOUNT_EMAIL_VERIFICATION = 'none'

# Bỏ qua trang xác nhận trung gian mặc định của allauth
# ("You are about to sign in using a third-party account...").
# Không có dòng này, bấm nút "Đăng nhập với Google/Facebook" sẽ hiện
# 1 trang xấu xí, không có giao diện của mình, trước khi sang Google thật.
# Có dòng này: bấm nút -> chuyển thẳng sang Google/Facebook luôn.
SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

# ── Thông tin ứng dụng Google / Facebook ──
# Lấy Client ID & Secret tại:
#   Google:   https://console.cloud.google.com/apis/credentials
#   Facebook: https://developers.facebook.com/apps
# Sau khi có, điền vào file .env với 4 biến bên dưới (KHÔNG hardcode trực tiếp ở đây).
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'facebook': {
        'APP': {
            'client_id': os.environ.get('FACEBOOK_CLIENT_ID', ''),
            'secret': os.environ.get('FACEBOOK_CLIENT_SECRET', ''),
            'key': '',
        },
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'FIELDS': ['id', 'email', 'name'],
    },
}

# ── Thông tin ứng dụng Zalo (xử lý thủ công trong views.py, xem zalo_login/zalo_callback) ──
# Đăng ký ứng dụng tại: https://developers.zalo.me/apps
ZALO_APP_ID = os.environ.get('ZALO_APP_ID', '')
ZALO_APP_SECRET = os.environ.get('ZALO_APP_SECRET', '')

# ============================================================
#  GỬI EMAIL — dùng cho chức năng "Quên mật khẩu?"
#  Mặc định: console backend — email sẽ được IN RA TERMINAL,
#  không cần cấu hình gì thêm, phù hợp để test khi đang phát triển.
#
#  Khi triển khai thật (production), đổi sang SMTP thật, ví dụ Gmail:
#    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#    EMAIL_HOST = 'smtp.gmail.com'
#    EMAIL_PORT = 587
#    EMAIL_USE_TLS = True
#    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')       # email Gmail
#    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD') # App Password 16 ký tự
#    (Gmail yêu cầu bật "App Passwords" trong cài đặt bảo mật tài khoản Google)
# ============================================================
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'Lotus Shop <no-reply@lotusshop.vn>'

# Thời gian hết hạn của link đặt lại mật khẩu (giây) — mặc định Django là 3 ngày (259200s)
PASSWORD_RESET_TIMEOUT = 259200